[package]
name = "twitter-text"
version = "0.2.0"
authors = ["Robert Sayre <sayrer@gmail.com>"]
readme = "README.md"
description = "An implementation of twitter-text in Rust."
license = "Apache-2.0"
repository = "https://github.com/sayrer/twitter-text"
edition = "2018"

[dependencies]
cxx = "0.3.4"
unicode-normalization = "0.1.25"
idna = "1.1.0"
pest = "2.8.4"
pest_derive = "2.8.4"
twitter_text_config = { path = "../config" , version = "0.2.0" }
twitter_text_parser = { path = "../parser" , version = "0.2.0" }
