[package]
name = "twitter_text_bindings_cargo"
version = "0.2.0"
authors = ["Robert Sayre <sayrer@gmail.com>"]
edition = "2021"

[dependencies]
clap = "4.5.53"
proc-macro-error = {version = "1.0.4"}
log = {version = "0.4.28", features = ["std"]}
cxx = "1.0.189"
pest = "2.8.4"
pest_derive = "2.8.4"
unicode-normalization = "0.1.25"
idna = "1.1.0"
lazy_static = "1.5.0"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
serde_yaml_ng = "0.10.0"
pyo3 = { version = "0.20", features = ["extension-module"] }
pyo3-macros = "0.20"
magnus = "0.8.2"
wasm-bindgen = "0.2"
js-sys = "0.3"

[[bin]]
name = "fake_bin"
path = "fake_bin.rs"
